### ISSUE TITLE
As a user who has just finished updating my information, I can see a message telling me I did the thing

### ISSUE THREAD

**Issue by heyitsolivia** [sunlightlabs/the-phantom-mask#12]
**General Copy needed**
- [ ] Note confirming the user updated their information successfully
- [ ] Identify (potentially new) reps and their email addresses, as well as myreps

![](https://raw.githubusercontent.com/sunlightlabs/the-phantom-mask/master/design/wireframes/views/change-of-address__success.png)

**Comment by nickom** [comment]
**Note confirming the user updated their information successfully**
Thanks for updating your information! You may now continue to message your representatives via email.

**Identify (potentially new) reps and their email addresses, as well as myreps**
Based on the updated address you gave us, you're in congressional district [State]-[Number]. Here's who represents you in the U.S. Congress:
[members listed]

Email all of them at once using MyReps @ opencongress.org
