### ISSUE TITLE
As a user, if I am overusing the service, I understand why I need to confirm that I'm not a spambot

### ISSUE THREAD

**Issue by heyitsolivia** [sunlightlabs/the-phantom-mask#14]
**Copy needed**
- [ ] Note about why we need to captcha
- [ ] A thank you/confirm that we sent off the message (after user submits)

![Captcha](https://raw.githubusercontent.com/sunlightlabs/the-phantom-mask/master/design/wireframes/views/captcha.png)

**Comment by nickom** [comment]
**Note at the top of the page**
It looks like you're emailing a lot! Please confirm your message so we know you're not a spambot:

[Message review]

[I am not a robot checkbox]

**Button**
Send my message now

**Comment by heyitsolivia** [comment]
We no longer need this since rate limit emails will make captcha's redundant.
