### ISSUE TITLE
As a user, I can reference a permanent page for my district that shows my reps

### ISSUE THREAD

**Issue by heyitsolivia** [sunlightlabs/the-phantom-mask#15]
**Copy needed**
- [ ] Explain purpose of this page
- [ ] Identify the user's reps and myreps
- [ ] Link to each rep's individual webform
- [ ] Show a map of the user's district

![District page](https://raw.githubusercontent.com/sunlightlabs/the-phantom-mask/master/design/wireframes/views/district-rep-permalink.png)

**Comment by nickom** [comment]
Remind me again what the purpose of this page is? How does a user even get here?

**Comment by heyitsolivia** [comment]
This is a permalink page of the user's reps, which gets linked to at the bottom of email footers as a way to remind and point users to their current reps and their contact info. Also possibly accessible from the success/confirmation messages at the end of signup or update web flows.

**Comment by nickom** [comment]
Gotcha, thanks @heyitsolivia. I think the page can just say:

Based on the updated address you gave us, you're in congressional district [State]-[Number]. Here's who represents you in the U.S. Congress:
[members listed]

Email all of them at once using MyReps @ opencongress.org
