### ISSUE TITLE
As a user, I can read a phantom-mask explainer before I sign up, so that I understand what this service provides

### ISSUE THREAD

**Issue by heyitsolivia** [sunlightlabs/the-phantom-mask#17]
- [ ] Write copy for an explanatory overview of the service
- [ ] Design graphics as needed to accompany or illustrate the explainer copy

**Comment by crdunwel** [comment]
relevant templates https://github.com/sunlightlabs/the-phantom-mask/blob/master/app/templates/emails/validate_user.html and https://github.com/sunlightlabs/the-phantom-mask/blob/master/app/templates/partials/explainer.html

**Comment by nickom** [comment]
Is this the first response a user gets if they aren't signed up? If so, here's the copy I wrote:

---

Subject: Completing your message to Congress

Body:
Hello!

It looks like you’re new to our email Congress system. We’ll need some information from you to be able to navigate congressional web forms and send your message along to your Senators and Representative. You’ll only need to do this once and you don’t need to know who represents you.

Click here to take the next step to contacting your representatives. [link to form]

Note: Members of Congress don’t have official emails. This service makes navigating their required web forms as easy as email. If you’d prefer to fill the web form of each member of Congress each time or would like another method of communication, look up your member of Congress [here](http://www.usa.gov/Contact/US-Congress.shtml#Contact_Your_Representative_in_the_U.S._Congress)

Thanks for using OpenCongress to contact Congress!
Sunlight Foundation

**Comment by heyitsolivia** [comment]
@nickom Oh, this is actually covered by the copy you wrote #8, for "Intro text that explains what the service does". Sorry for the confusion—this is mostly a design task.

**Comment by nickom** [comment]
@heyitsolivia gotcha

**Comment by heyitsolivia** [comment]
@nickom nope I take back what I said. After dropping in the copy for the explainer/intro text into the design comps, it looks like we may need to rethink it a little bit for it to make sense.

**Comment by nickom** [comment]
New first sentence?

Members of Congress don't have email addresses but this service from the Sunlight Foundation will allow you to message your representatives by email.
