### ISSUE TITLE
Phantom mask emails should be delivered as a reply to user's original email

### ISSUE THREAD

**Issue by heyitsolivia** [sunlightlabs/the-phantom-mask#28]

**Comment by crdunwel** [comment]
See https://github.com/sunlightlabs/the-phantom-mask/commit/92efea8b3b763dc27647438713d114e0fe82cd99 . Just need to drop in the header so will add to other messages as needed as we finalize.

**Comment by heyitsolivia** [comment]
Looks like these are coming back as replies in Gmail, Apple Mail, and Thunderbird.

Worth testing a little more before we close this issue.
