### ISSUE TITLE
Improve form validation error styling

### ISSUE THREAD

**Issue by heyitsolivia** [sunlightlabs/the-phantom-mask#34]
We need styles for form error messages (non-existent right now).

Form errors appear both inline and in summary. (Inline error messages appear for browsers that don't support the HTML **required** form validation, like Safari and Safari ios).

![screen shot 2015-06-22 at 4 48 15 pm](https://cloud.githubusercontent.com/assets/1198350/8292594/88413576-18fe-11e5-98d3-d177bdd6c1cb.png)

![img_3769](https://cloud.githubusercontent.com/assets/1198350/8292527/302f86da-18fe-11e5-8c26-8cd81d5b532d.PNG)

**Comment by heyitsolivia** [comment]
## Progress notes

cc @crdunwel 

1) Form errors element should only be shown if errors exist. Templating thing. 

<img width="538" alt="screen shot 2015-07-03 at 4 33 02 pm" src="https://cloud.githubusercontent.com/assets/1198350/8504530/51d2f3e8-21a1-11e5-9d5c-c107ec48b169.png">

2) Select inputs (title and state) need better error messaging than "Not a valid choice." Placeholder/defaults throw this validation off.

3) City and State fields should be revealed post form submission. Right now, they remain hidden.

4) We need a better way to handle zipcode error messages. The two sections of the zipcode are being treated as two separate error messages… confusing.

5) It would make sense to have error messages listed in a way that parallels the order of the fields in the forms. Not sure why it seems to be random right now.

<img width="535" alt="screen shot 2015-07-03 at 4 35 56 pm" src="https://cloud.githubusercontent.com/assets/1198350/8504552/a2b8f19a-21a1-11e5-8726-6b7f3c913140.png">

**Comment by heyitsolivia** [comment]
Remaining task here:
- Merge the two zipcode error messages into a single one. cc @crdunwel
- Add `.is-invalid` styling for select inputs

**Comment by crdunwel** [comment]
![screen shot 2015-07-10 at 1 19 46 pm](https://cloud.githubusercontent.com/assets/942819/8624515/6215dd8c-2706-11e5-83b2-a230da3e161c.png)

**Comment by heyitsolivia** [comment]
added invalid state styles for select elements in dd092c229c0fc6aab10c73eee49690b5e644d032
