### ISSUE TITLE
Input masks in address form are not working in safari

### ISSUE THREAD

**Issue by heyitsolivia** [sunlightlabs/the-phantom-mask#39]
:disappointed: 

<img width="531" alt="screen shot 2015-07-03 at 3 45 10 pm" src="https://cloud.githubusercontent.com/assets/1198350/8504171/8ad192e6-219a-11e5-909e-f76d806188c8.png">

**Comment by crdunwel** [comment]
![screen shot 2015-07-09 at 2 28 39 pm](https://cloud.githubusercontent.com/assets/942819/8603527/d982b860-2646-11e5-9e7c-6c64a52dfc7a.png)

works for me in safari?

**Comment by heyitsolivia** [comment]
hahaha. nevermind.
