### ISSUE TITLE
Need template hooks to add classes to invalid fields

### ISSUE THREAD

**Issue by heyitsolivia** [sunlightlabs/the-phantom-mask#40]
After the signup form is submitted, we need to be able to visually denote which form fields need attention from the user. We could do that by adding a class to the input element but need template hooks to do that.

<img width="478" alt="screen shot 2015-07-03 at 4 00 04 pm" src="https://cloud.githubusercontent.com/assets/1198350/8504275/a4abe62e-219c-11e5-8b90-668dcc3e3553.png">

**Comment by heyitsolivia** [comment]
resolved in 0a80701362f94860f93196617c76b734e7d49e06

**Comment by crdunwel** [comment]
The <select> elements weren't displaying red like the <input> ones. Did you fix that?
