### ISSUE TITLE
Add confirmation emails for different states

### ISSUE THREAD

**Issue by heyitsolivia** [sunlightlabs/the-phantom-mask#42]
Still need the following emails:
- [x] Account created
- [x] Success: message sent
- [x] Failure: message not sent
- [x] Success: address updated

**Comment by crdunwel** [comment]
@heyitsolivia - I don't think these exist in the markup that @ngrad gave me.

**Comment by heyitsolivia** [comment]
@crd not all of the content/copy exists in the markup but I think all of the styles for each state are present.

Check https://github.com/sunlightlabs/the-phantom-mask/tree/master/design/comps/email for mockups of each state if you need them.

**Comment by crdunwel** [comment]
kk

**Comment by crdunwel** [comment]
@heyitsolivia Try naive case expecting everything to work with proper input?
