### ISSUE TITLE
Form validation needed in confirm_reps view

### ISSUE THREAD

**Issue by heyitsolivia** [sunlightlabs/the-phantom-mask#44]
We need some form validation to make sure the user has selected at least one rep to contact (if they choose to send their message).

to prevent this:

![screen shot 2015-07-10 at 5 58 32 pm](https://cloud.githubusercontent.com/assets/1198350/8635551/da845b28-27f5-11e5-9fae-0fd162d20ca4.png)

**Comment by heyitsolivia** [comment]
This validation can be handled like this (according to our design mockups)

![screen shot 2015-07-15 at 12 35 56 pm](https://cloud.githubusercontent.com/assets/1198350/8703964/163a6c7a-2aee-11e5-9951-8e28a0b88753.png)

**Comment by heyitsolivia** [comment]
created a `is-disabled` class for the primary button in c82a91eac4542f1f6f9bd7479a047ad8b0ae95a1

**Comment by crdunwel** [comment]
@heyitsolivia see https://github.com/sunlightlabs/the-phantom-mask/commit/30ce778caf0705df89825194b1741cfaac19dceb
