### ISSUE TITLE
All links within the webform should open up in a new window/tab

### ISSUE THREAD

**Issue by heyitsolivia** [sunlightlabs/the-phantom-mask#47]
All of these links in the screenshot below open in the same window, causing the user to navigate away from the form, resulting in sadness, also confusion.

Comments from user testing include:

> Usually on pages with forms, I expect to get a popup saying that I’m about to leave the page.
> 
> arrrgh 
> 
> oh no did I just lose all my info

<img width="747" alt="screen shot 2015-07-21 at 11 43 26 pm" src="https://cloud.githubusercontent.com/assets/1198350/8817538/50168c9e-3002-11e5-8b41-44a74bbacb55.png">

**Comment by crdunwel** [comment]
@heyitsolivia FAQ/ToS/Privacy too?
