### ISSUE TITLE
Wireframes for new landing page

### ISSUE THREAD

**Issue by heyitsolivia** [sunlightlabs/the-phantom-mask#63]
Needs the following components:
- [x] Overview
- [x] Sign up button
- [x] Remind me who my reps are/lookup
- [x] Change my address/info
- [x] 3 step process explaining "How"
- [x] Section explaining why this tool was created
- [x] Footer

**Comment by heyitsolivia** [comment]
Wirestorm and landing page user flows

![landing-wirestorm](https://cloud.githubusercontent.com/assets/1198350/8992408/41c24658-36cc-11e5-9160-5d8391bedc7f.jpg)

![landing-page-user-flow](https://cloud.githubusercontent.com/assets/1198350/8992345/fdda15b0-36cb-11e5-8f09-212423e668c2.jpg)

**Comment by heyitsolivia** [comment]
![wireframe](https://cloud.githubusercontent.com/assets/1198350/9071552/dd0c6fd0-3ac3-11e5-93dd-531bd82c32ea.jpg)

**Comment by heyitsolivia** [comment]
Posted this in this commit: a55585a97bae1101d3907eae7a3090c7dbe95d11

![wireframe of homepage](https://raw.githubusercontent.com/sunlightlabs/the-phantom-mask/master/design/wireframes/views/homepage.png)

**Comment by crdunwel** [comment]
@heyitsolivia Looks great, will churn something out asap.

**Comment by heyitsolivia** [comment]
Still need to show what these actual states and actions look like:
(on the same page)
- [ ] Signing up
- [ ] Remind me who my reps are/lookup
- [ ] Change my address/info

**Comment by crdunwel** [comment]
@heyitsolivia https://github.com/sunlightlabs/the-phantom-mask/commit/721d8c23cb269dc9029d2494a2c30bafddba2386

Set up index "/" route (locally, http://localhost:5000/ ) and basic template. Let's briefly discuss how you'd like me to go about trying to style.
